# Generated by Django 3.2.3 on 2021-05-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0002_auto_20210521_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='pub_date',
            new_name='date_posted',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='pub_date',
            new_name='date_posted',
        ),
        migrations.AddField(
            model_name='post',
            name='post_title',
            field=models.CharField(default='Başlık', max_length=100),
        ),
    ]
