# Generated by Django 3.2.3 on 2021-05-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0003_auto_20210521_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_icerik', models.CharField(default='Yeni Üye', max_length=100)),
                ('status_user', models.CharField(default='admin', max_length=200)),
            ],
        ),
    ]
