# Generated by Django 3.2.3 on 2021-05-22 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0006_alter_post_post_icerik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_icerik',
            field=models.TextField(),
        ),
    ]
