# Generated by Django 3.2.3 on 2021-05-24 15:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0009_auto_20210523_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_icerik',
            field=models.TextField(verbose_name='Yorum'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_commented',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 24, 18, 34, 15, 21391), verbose_name='yorum tarihi'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='original_commenter',
            field=models.CharField(default='anonymous', max_length=200),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Posts.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 24, 18, 34, 15, 21391), verbose_name='paylaşım tarihi'),
        ),
    ]
