# Generated by Django 3.2.3 on 2021-05-24 20:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0010_auto_20210524_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_commented',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 24, 23, 51, 59, 354953), verbose_name='yorum tarihi'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 24, 23, 51, 59, 354953), verbose_name='paylaşım tarihi'),
        ),
    ]
