# Generated by Django 3.2.3 on 2021-05-24 21:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0012_auto_20210525_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_commented',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 25, 0, 39, 32, 742612), verbose_name='yorum tarihi'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 25, 0, 39, 32, 741569), verbose_name='paylaşım tarihi'),
        ),
    ]
