# Generated by Django 3.2.3 on 2021-05-24 23:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0013_auto_20210525_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_icerik',
            field=models.TextField(default='', verbose_name='Yorum'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_commented',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 25, 2, 30, 56, 289474), verbose_name='yorum tarihi'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 25, 2, 30, 56, 289474), verbose_name='paylaşım tarihi'),
        ),
    ]
