# Generated by Django 3.2.3 on 2021-05-25 11:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0015_auto_20210525_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_commented',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 25, 14, 36, 41, 571310), verbose_name='yorum tarihi'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 25, 14, 36, 41, 571310), verbose_name='paylaşım tarihi'),
        ),
    ]
